# frozen_string_literal: true

namespace :rspec_tracer do
  namespace :remote_cache do
    desc 'Download cache'
    task :download do
      require 'rspec_tracer'

      unless system('git', 'rev-parse', 'HEAD', out: File::NULL, err: File::NULL)
        RSpecTracer.logger.error 'Not a git repository'

        exit
      end

      RSpecTracer::RemoteCache::Cache.new.download
    end

    desc 'Upload cache'
    task :upload do
      require 'rspec_tracer'

      unless system('git', 'rev-parse', 'HEAD', out: File::NULL, err: File::NULL)
        RSpecTracer.logger.error 'Not a git repository'

        exit
      end

      unless ENV['CI'] == 'true' || RSpecTracer.upload_non_ci_reports
        RSpecTracer.logger.warn 'Uploading reports from a non CI environment is disabled'

        exit
      end

      RSpecTracer::RemoteCache::Cache.new.upload
    end
  end
end
