version: "2"
checks:
  file-lines:
    config:
      threshold: 500
  method-complexity:
    config:
      threshold: 15
  method-count:
    config:
      threshold: 50
  similar-code:
    config:
      threshold: 50
  identical-code:
    config:
      threshold: 50
plugins:
  duplication:
    enabled: true
    exclude_patterns:
      - "spec/"
exclude_patterns:
  - "Gemfile"
  - "Gemfile.lock"
  - "LICENSE"
  - "rspec-tracer.gemspec"
  - "**/Rakefile"
  - "**/.*"
  - "**/*.md"
  - "**/*.rake"
  - "coverage/"
  - "rspec_tracer_cache/"
  - "rspec_tracer_coverage/"
  - "rspec_tracer_report/"
  - "lib/rspec_tracer/html_reporter/"
  - "!lib/rspec_tracer/**/*.rb"
  - "features/"
  - "!features/**/*.rb"
  - "readme_files/"
  - "sample_projects/"
  - "tmp/"
