version: "2"
checks:
  file-lines:
    config:
      threshold: 300
  method-complexity:
    config:
      threshold: 10
  method-count:
    config:
      threshold: 50
  similar-code:
    config:
      threshold: 50
  identical-code:
    config:
      threshold: 50
plugins:
  duplication:
    enabled: true
    exclude_patterns:
      - "spec/"
exclude_patterns:
  - "lib/rspec_tracer/html_reporter/assets/"
  - "lib/rspec_tracer/html_reporter/public/"
  - "features/data/"
  - "readme_files/"
  - "sample_projects/"
  - "tmp/"
