# frozen_string_literal: true

# Path strings near the OS PATH_MAX (Linux 4096 / macOS 1024) round-trip
# without truncation through every backend. Long descriptions, long
# env values, and deeply-nested directory paths all show up in the
# wild (autogenerated paths in monorepos, deeply-nested package
# trees, descriptive `let_it_be(:user) { ... }` names).
#
# Note: this is a content test, not a "create file at OS-limit
# path" test. The cache filenames themselves are short (FILENAMES
# constant); the path strings live as VALUES inside those files.
# Backend round-trip is the contract under test.
#
# NAME_MAX (single component limit) is 255 on every supported OS;
# this spec stays under that for any path COMPONENT, then exceeds
# PATH_MAX in the aggregate via deep nesting.

require 'fileutils'
require 'set'
require 'tmpdir'
require 'rspec_tracer/storage/json_backend'
require 'rspec_tracer/storage/snapshot'

LONG_PATH_SQLITE_AVAILABLE =
  begin
    require 'sqlite3'
    require 'rspec_tracer/storage/sqlite_backend'
    RUBY_ENGINE == 'ruby'
  rescue LoadError
    false
  end

# Build path strings of varying lengths via repetition, so the spec
# source stays short and reproducible.
module LongPathGen
  module_function

  # Single-component path with a name near NAME_MAX (255 chars, leaving
  # 4 for the .rb extension).
  def near_name_max
    "/spec/#{'a' * 250}.rb"
  end

  # Deep nesting that aggregates well over PATH_MAX (4096 on Linux).
  def beyond_path_max
    segments = (1..200).map { |i| "deep#{i.to_s.rjust(3, '0')}" }
    "/#{segments.join('/')}/spec_under_test.rb"
  end

  # Long string value (8 KiB) for description / env value / digest.
  def long_string
    'x' * (8 * 1024)
  end

  # Realistic-shape path (typical Rails monorepo nesting).
  def realistic_long
    "/#{'app/' * 60}models/sub_model.rb"
  end
end

# rubocop:disable RSpec/DescribeClass
RSpec.describe 'Long paths + long string values in cache content' do
  let(:tmp_base) { Dir.mktmpdir('rspec_tracer_long_path_') }
  let(:cache_path) { File.join(tmp_base, 'cache') }
  let(:schema_version) { RSpecTracer::Storage::Schema::CURRENT }

  after { FileUtils.rm_rf(tmp_base) if tmp_base }

  def build_long_snapshot(run_id)
    near_name = LongPathGen.near_name_max
    deep = LongPathGen.beyond_path_max
    realistic = LongPathGen.realistic_long
    long_desc = LongPathGen.long_string

    RSpecTracer::Storage::Snapshot.new(
      schema_version: RSpecTracer::Storage::Schema::CURRENT,
      run_id: run_id,
      all_examples: {
        'ex_near' => { id: 'ex_near', description: long_desc, file_path: near_name },
        'ex_deep' => { id: 'ex_deep', description: 'short', file_path: deep },
        'ex_realistic' => { id: 'ex_realistic', description: 'medium', file_path: realistic }
      },
      duplicate_examples: {},
      interrupted_examples: Set.new,
      flaky_examples: Set.new,
      failed_examples: Set.new,
      pending_examples: Set.new,
      skipped_examples: Set.new,
      all_files: {
        near_name => { file_name: near_name, file_path: near_name, digest: 'a' * 64 },
        deep => { file_name: deep, file_path: deep, digest: 'b' * 64 },
        realistic => { file_name: realistic, file_path: realistic, digest: 'c' * 64 }
      },
      dependency: {
        'ex_near' => Set.new([near_name]),
        'ex_deep' => Set.new([deep]),
        'ex_realistic' => Set.new([realistic])
      },
      reverse_dependency: {
        near_name => Set.new(['ex_near']),
        deep => Set.new(['ex_deep']),
        realistic => Set.new(['ex_realistic'])
      },
      examples_coverage: {
        'ex_near' => { near_name => [1] },
        'ex_deep' => { deep => [1] },
        'ex_realistic' => { realistic => [1] }
      },
      boot_set: { deep => 'deadbeef', realistic => 'cafef00d' },
      wsi_snapshot: {},
      env_snapshot: { 'LONG_VAR' => long_desc },
      env_dependency: { 'ex_near' => ['LONG_VAR'] }
    )
  end

  shared_examples 'round-trips long paths + long strings' do
    it 'preserves a path with a 250-char single component (near NAME_MAX)' do
      snap = backend.load_graph(schema_version: schema_version)

      expect(snap.all_files).to have_key(LongPathGen.near_name_max)
    end

    it 'preserves a deeply-nested path well beyond PATH_MAX in the aggregate' do
      snap = backend.load_graph(schema_version: schema_version)

      expect(snap.all_files).to have_key(LongPathGen.beyond_path_max)
      expect(LongPathGen.beyond_path_max.bytesize).to be > 1024 # actually beyond all OS PATH_MAX
    end

    it 'preserves a realistic Rails-monorepo-shape long path' do
      snap = backend.load_graph(schema_version: schema_version)

      expect(snap.dependency.fetch('ex_realistic')).to include(LongPathGen.realistic_long)
    end

    it 'preserves an 8 KiB description string without truncation' do
      snap = backend.load_graph(schema_version: schema_version)

      expect(snap.all_examples['ex_near'][:description].bytesize).to eq(8 * 1024)
    end

    it 'preserves an 8 KiB env_snapshot value' do
      snap = backend.load_graph(schema_version: schema_version)

      expect(snap.env_snapshot.fetch('LONG_VAR').bytesize).to eq(8 * 1024)
    end
  end

  describe 'JsonBackend :json' do
    let(:backend) { RSpecTracer::Storage::JsonBackend.new(cache_path: cache_path, serializer: :json) }

    before { backend.save_graph(build_long_snapshot('run-long-json'), schema_version: schema_version) }

    it_behaves_like 'round-trips long paths + long strings'
  end

  describe 'JsonBackend :msgpack' do
    let(:backend) { RSpecTracer::Storage::JsonBackend.new(cache_path: cache_path, serializer: :msgpack) }

    before { backend.save_graph(build_long_snapshot('run-long-msgpack'), schema_version: schema_version) }

    it_behaves_like 'round-trips long paths + long strings'
  end

  describe 'SqliteBackend' do
    before do
      skip 'sqlite3 gem not installable on this Ruby (JRuby or missing dep)' unless LONG_PATH_SQLITE_AVAILABLE
      backend.save_graph(build_long_snapshot('run-long-sqlite'), schema_version: schema_version)
    end

    let(:backend) { RSpecTracer::Storage::SqliteBackend.new(cache_path: cache_path) }

    it_behaves_like 'round-trips long paths + long strings'
  end
end
# rubocop:enable RSpec/DescribeClass
