# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rails', ENV['RAILS_VERSION']
gem 'sqlite3', '~> 1.4'
gem 'puma', '~> 5.0'
gem 'jbuilder', '~> 2.7'
gem 'bootsnap', '>= 1.4.4', require: false

group :development, :test do
  gem 'pry'
  gem 'simplecov', ENV['SIMPLECOV_VERSION']
end

group :development do
  gem 'web-console'
  gem 'spring'
end

group :test do
  gem 'rspec-rails', ENV['RSPEC_RAILS_VERSION']
  gem 'rspec-tracer', path: '../../..', require: false
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
