# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rails', ENV['RAILS_VERSION']
# Rails 7.0/7.1's activerecord locks `sqlite3 ~> 1.4` at load time
# (inside sqlite3_adapter.rb), not in its gemspec, so bundler can resolve
# to 2.x and then the gem activation blows up. Rails 8.0 needs
# sqlite3 >= 2.1. Pick the right major via env var from the workflow.
gem 'sqlite3', ENV.fetch('SQLITE3_VERSION', '~> 1.4')
gem 'puma', '~> 6.0'
gem 'jbuilder', '~> 2.7'
gem 'bootsnap', '>= 1.4.4', require: false

group :development, :test do
  gem 'pry'
  gem 'simplecov', '~> 0.22'
end

group :test do
  gem 'rspec-rails', ENV['RSPEC_RAILS_VERSION']
  gem 'rspec-tracer', path: '../../..', require: false
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
