name: lint-and-specs

on:
  push:
    branches: [ 'main' ]
  pull_request:

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  main:
    name: ruby-${{ matrix.ruby }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.5', '2.6', '2.7', '3.0', 'head' ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install Dependencies
        run: bundle install --jobs 3 --retry 3

      - name: Run Rubocop
        run: bundle exec rake rubocop

      - name: Run Specs
        run: bundle exec rake spec
