name: ruby-project-part-2

on:
  push:
    branches: [ 'main' ]
  pull_request:

concurrency:
  group: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}-ruby-2
  cancel-in-progress: true

jobs:
  main:
    name: ruby-${{ matrix.ruby }} rspec-${{ matrix.rspec }} simplecov-${{ matrix.simplecov }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.5', '2.6', '2.7', '3.0', 'head' ]
        rspec: [ '3.6.0', '3.7.0', '3.8.0', '3.9.0', '3.10.0' ]
        simplecov: [ '0.18.0', '0.19.0', '0.20.0', '0.21.0' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install Dependencies
        run:  bundle install --jobs 3 --retry 3

      - name: Run Features for Ruby Project
        env:
          RSPEC_VERSION: "~> ${{ matrix.rspec }}"
          SIMPLECOV_VERSION: "~> ${{ matrix.simplecov }}"
          BRANCH_COVERAGE: true
        run: bundle exec cucumber --tags @ruby-app
